apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-min-side-oversikt
  namespace: min-side
  labels:
    team: min-side
  annotations:
    config.linkerd.io/proxy-memory-limit: "512Mi"
    config.linkerd.io/proxy-memory-request: "128Mi"
spec:
  envFrom:
    - secret: tms-min-side-oversikt-secrets
  image: {{image}}
  port: 7500
  liveness:
    path: /tms-min-side-oversikt/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-min-side-oversikt/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /tms-min-side-oversikt/internal/metrics
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://person.intern.nav.no/tms-min-side-oversikt"
    - "https://www.nav.no/tms-min-side-oversikt"
  resources:
    limits:
      cpu: "3"
      memory: 1268Mi
    requests:
      cpu: "500m"
      memory: 1024Mi
